# Generated by Django 4.0.6 on 2022-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='next_destination',
            field=models.IntegerField(null=True),
        ),
    ]
