# Generated by Django 4.0.6 on 2022-07-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_elevator_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
