# Generated by Django 4.0.6 on 2022-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_elevator_is_working"),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="completes_by",
            field=models.IntegerField(default=0),
        ),
    ]
