# Generated by Django 4.0.6 on 2022-08-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_requests_completes_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='completes_by',
            field=models.BigIntegerField(null=True),
        ),
    ]
